-- MySQL Script generated by MySQL Workbench
-- Fri May 22 01:39:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema memmet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema memmet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `memmet` DEFAULT CHARACTER SET utf8 ;
USE `memmet` ;

-- -----------------------------------------------------
-- Table `memmet`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memmet`.`User` (
  `correoUser` VARCHAR(320) NOT NULL,
  `nickUser` VARCHAR(45) NOT NULL,
  `passwordUser` VARCHAR(50) NULL,
  `tipoUser` VARCHAR(10) NULL,
  `nivelUser` INT NULL,
  `avatarUser` VARCHAR(500) NULL,
  PRIMARY KEY (`correoUser`),
  UNIQUE INDEX `nickUser_UNIQUE` (`nickUser` ASC),
  UNIQUE INDEX `correoUser_UNIQUE` (`correoUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memmet`.`Meme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memmet`.`Meme` (
  `idMeme` INT NOT NULL AUTO_INCREMENT,
  `fechaMeme` VARCHAR(45) NULL,
  `rutaMeme` VARCHAR(500) NULL,
  `User_correoUser` VARCHAR(320) NOT NULL,
  PRIMARY KEY (`idMeme`),
  INDEX `fk_Meme_User_idx` (`User_correoUser` ASC),
  CONSTRAINT `fk_Meme_User`
    FOREIGN KEY (`User_correoUser`)
    REFERENCES `memmet`.`User` (`correoUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memmet`.`Puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memmet`.`Puntuacion` (
  `User_correoUser` VARCHAR(320) NOT NULL,
  `Meme_idMeme` INT NOT NULL,
  `valorPuntuacion` TINYINT NULL,
  INDEX `fk_Puntuacion_User1_idx` (`User_correoUser` ASC),
  INDEX `fk_Puntuacion_Meme1_idx` (`Meme_idMeme` ASC),
  CONSTRAINT `fk_Puntuacion_User1`
    FOREIGN KEY (`User_correoUser`)
    REFERENCES `memmet`.`User` (`correoUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puntuacion_Meme1`
    FOREIGN KEY (`Meme_idMeme`)
    REFERENCES `memmet`.`Meme` (`idMeme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memmet`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memmet`.`Tag` (
  `nombreTag` VARCHAR(320) NOT NULL,
  PRIMARY KEY (`nombreTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memmet`.`Suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memmet`.`Suscripcion` (
  `User_correoUser` VARCHAR(320) NOT NULL,
  `Tag_nombreTag` VARCHAR(230) NOT NULL,
  `ignora` TINYINT NULL,
  INDEX `fk_Ignorados_User1_idx` (`User_correoUser` ASC),
  INDEX `fk_Ignorados_Tag1_idx` (`Tag_nombreTag` ASC),
  PRIMARY KEY (`User_correoUser`, `Tag_nombreTag`),
  CONSTRAINT `fk_Ignorados_User1`
    FOREIGN KEY (`User_correoUser`)
    REFERENCES `memmet`.`User` (`correoUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ignorados_Tag1`
    FOREIGN KEY (`Tag_nombreTag`)
    REFERENCES `memmet`.`Tag` (`nombreTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `memmet`.`Tag_has_Meme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memmet`.`Tag_has_Meme` (
  `Tag_nombreTag` VARCHAR(320) NOT NULL,
  `Meme_idMeme` INT NOT NULL,
  PRIMARY KEY (`Tag_nombreTag`, `Meme_idMeme`),
  INDEX `fk_Tag_has_Meme_Meme1_idx` (`Meme_idMeme` ASC),
  INDEX `fk_Tag_has_Meme_Tag1_idx` (`Tag_nombreTag` ASC),
  CONSTRAINT `fk_Tag_has_Meme_Tag1`
    FOREIGN KEY (`Tag_nombreTag`)
    REFERENCES `memmet`.`Tag` (`nombreTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_Meme_Meme1`
    FOREIGN KEY (`Meme_idMeme`)
    REFERENCES `memmet`.`Meme` (`idMeme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
